[package]
name = "dscribe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

mavlink = { version = "0.10.1", features = ["common","uavionix", "icarous", "ardupilotmega"] }
